### ISSUE TITLE
No KMS traces

### ISSUE THREAD

**Issue by nzoschke** [aws/aws-xray-sdk-go#42] opened 2018-02-03 20:06 UTC
I'm not seeing KMS service calls in my traces, despite wrapping the KMS client with `xray.AWS()`.

I noticed the SDK has a whitelist that does not include KMS. Is it up to me to add KMS, etc to a custom whitelist in my code? Would you consider adding it to the default whitelist?

**Comment by awssandra** [comment] 2018-02-05 17:43
Hi nzoschke,

The default whitelist defines the call parameters to capture from AWS API calls, as some parameters may contain sensitive data. The calls themselves (service, time, API) should always be recorded.

Can you tell me which version you're using and provide a small snippet so we can try and reproduce the issue on our end?

Thank you!
Sandra

**Comment by nzoschke** [comment] 2018-02-08 07:31
I'm using 1.0.0-rc.1. Here's a snippet:

```

func KMS() *kms.KMS {
	cfg := &aws.Config{
		Region: aws.String("us-east-1"),
	}

	sess, err := session.NewSession(cfg)
	if err != nil {
		panic(err)
	}

	c := kms.New(sess)
	xray.AWS(c.Client)
	return c
}

func Handle() {
	out, err := KMS().EncryptWithContext(ctx, &kms.EncryptInput{
		Plaintext: b,
		KeyId:     aws.String(id),
	})
	if err != nil {
		return nil, errors.WithStack(err)
	}
}
```

**Comment by awssandra** [comment] 2018-02-12 22:16
Hi nzoschke,

I have been unable to reproduce the issue. Here's the KMS subsegment generated: 
```
 "subsegments": [
  {
   "id": "a72a9316a2f76085",
   "name": "kms",
   "start_time": 1518472358.3725019,
   "end_time": 1518472358.7610471,
   ...
   },
   "namespace": "aws",
   "http": {
    "response": {
     "status": 400,
     "content_length": 56
    }
   },
   "aws": {
    "operation": "Encrypt",
    "region": "us-east-1",
    "request_id": "xxxxxxxxxxxx",
    "retries": 0
   },
   "subsegments": [ ... ]
  }
```
Here's the (modified) code I used:
```
func KMS() *kms.KMS {
  sess, err := session.NewSession(&aws.Config{ Region: aws.String("us-east-1") })
  if err != nil {
    panic(err)
  }

  c := kms.New(sess)
  xray.AWS(c.Client)
  return c
}

func Handle(ctx context.Context) string {
  out, err := KMS().EncryptWithContext(ctx, &kms.EncryptInput{
    Plaintext: []byte("secret"),
    KeyId:     aws.String(KEY_ID),
  })
  if err != nil {
    return errors.WithStack(err).Error()
  }

  return out.GoString()
}

func main() {
  namer := xray.NewFixedSegmentNamer("MyApp")

  http.Handle("/", xray.Handler(namer, http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
    out := Handle(r.Context())
    w.Write([]byte(out))
  })))

  http.ListenAndServe(":8000", nil)
}
```
In the original code, I did not see how you were accessing the ctx for the KMS().EncryptWithContext call. Here I'm just pulling it off the request object (r.Context()) and passing it in.

If you set LogLevel to "trace" and post the results here, I'd like to see what the X-Ray SDK logs in the background.

**Comment by awssandra** [comment] 2018-02-21 18:56
Closing this at the moment - comment and I can reopen if any further issues are seen.

**Closed by awssandra** 2018-02-21 18:56 UTC
Labels: question, work-in-progress

**Comment by nzoschke** [comment] 2018-02-27 18:24
Sorry for the delay, but I finally reviewed my code and do see KMS traces. Sorry for the false alarm and thanks for looking into it.
