### ISSUE TITLE
deferred func acts on nil segment

### ISSUE THREAD

**Issue by snikch** [aws/aws-xray-sdk-go#41] opened 2018-02-01 02:24 UTC
Without adding tracing to a request, we're running into a nil pointer issue with this code. Basically it's in an if statement that has confirmed the `seg` var is nil, and then it tries to access its properties.

https://github.com/aws/aws-xray-sdk-go/blob/master/xray/capture.go#L26

**Comment by luluzhao** [comment] 2018-02-01 19:53
@snikch , thank you so much for reaching out to us. Could you give me more information regarding your issue? I want to reproduce it to see what happened. What's more, have you seen panic in your code? What is the message?

**Comment by luluzhao** [comment] 2018-02-03 00:04
@snikch , I agree with you that the issue happened because of if else block. We should give a better error message to address the real problem. We will add this issue into our backlog to fix it.

**Comment by dgorohov** [comment] 2018-03-14 20:48
Same for me
The problem is here: https://github.com/aws/aws-xray-sdk-go/blob/master/xray/capture.go#L21

**Comment by NZKoz** [comment] 2018-03-21 02:57
@luluzhao do you have an update for us here?  The issue we're having is that we want to instrument a bunch of core libraries so we can have calls coming into the traced HTTPClient which may or may not have segments in the context.  

We're working around this at present but it's kinda messy...

**Comment by luluzhao** [comment] 2018-03-21 19:15
@NZKoz sorry for the inconvenience. It is in our backlog and we will address it as soon as possible. If we fix this issue, I will update this thread immediately. Thank you for your patience.

**Comment by luluzhao** [comment] 2018-03-22 21:36
@NZKoz @dgorohov @snikch , hello all, I just release v1.0.0-rc.2 for X-Ray Go SDK which contains the bug fix for this issue. Feel free to upgrade our SDK and start using it. If it works, please close this issue. Thank you.

**Closed** 2018-04-05 00:59 UTC
