### ISSUE TITLE
Support AWS SDK for Go v2 

### ISSUE THREAD

**Issue by johanneswuerbach** [aws/aws-xray-sdk-go#277] opened 2021-01-29 00:26 UTC
The AWS SDK for Go v2 v1.0.0 has been released a few days ago. It would be great if the new SDK version would also be instrumentable like the v1 SDK.

Currently instrumenting a v2 SDK clients like:

```
s3Client := s3.NewFromConfig(cfg)
xray.AWS(s3Client)
```

fails with: `cannot use s3Client (variable of type *s3.Client) as *client.Client value in argument to xray.AWS`

**Comment by awssandra** [comment] 2021-01-29 18:22
Hi johanneswuerbach,

Unfortunately because the AWS SDK team has done foundational changes to the core APIs and request handling in the V2 rework, well need to dive into the new stack for AWS SDK V2 support.

https://aws.github.io/aws-sdk-go-v2/docs/middleware/

We will add this into our feature backlog, and we are happy to work with the community on PRs.

**Comment by lukestoward** [comment] 2021-03-05 10:10
I also am keen to see this support added. Right now, this is a barrier for adoption of the Go SDK v2 as we don't want to lose tracing.

**Comment by wangzlei** [comment] 2021-03-15 21:15
There is solution for aws go sdk v2 in OpenTelemetry by middleware, it would be good if someone can help to migrate to here.
https://github.com/open-telemetry/opentelemetry-go-contrib/pull/621

**Comment by wangzlei** [comment] 2021-03-24 00:03
https://github.com/open-telemetry/opentelemetry-go-contrib/pull/621 is merged

**Comment by johanneswuerbach** [comment] 2021-03-24 00:37
@wangzlei looks like this has been closed by accident or is the opentelemetry based instrumentation supposed to replace xray? If yes, is there any documentation how to configure it?

**Comment by stevefchambers** [comment] 2021-04-02 21:41
@awssandra @wangzlei -- Any thoughts on posting some documentation here on how to use the opentelemetry solution?

**Comment by kevinmcconnell** [comment] 2021-04-23 07:31
@awssandra could you provide an update on whether v2 support is still on the backlog?

The fact that there is a 3rd-party project that supports it does not seem like it addresses the original issue here.  Or does the introduction of the v2 SDK effectively mean the end of any official AWS support for using X-Ray with Go?

**Comment by ferradario** [comment] 2021-06-10 14:24
@awssandra, as @kevinmcconnell said it would be nice to understand the timeline for this. Anywhere we can refer to?

**Comment by bhautikpip** [comment] 2021-06-11 10:34
@ferradario currently we don't have a timeline for this work. I will try to  look at this PR - https://github.com/aws/aws-xray-sdk-go/pull/297 on what work needs to be done in order to add this support. However, we are tracking ToDos in the PR itself.

**Comment by adamantike** [comment] 2021-07-05 15:53
Will this be solved after a release is tagged, including merged PR #309?

**Comment by bhautikpip** [comment] 2021-07-07 20:22
X-Ray Go SDK `v1.6.0` is now released which includes aws sdk v2 support.

**Closed** 2021-07-07 20:23 UTC
Labels: enhancement, feature-request

**Comment by DanielBauman88** [comment] 2022-06-08 22:19
> The AWS SDK for Go v2 v1.0.0 has been released a few days ago. It would be great if the new SDK version would also be instrumentable like the v1 SDK.
> 
> Currently instrumenting a v2 SDK clients like:
> 
> ```
> s3Client := s3.NewFromConfig(cfg)
> xray.AWS(s3Client)
> ```
> 
> fails with: `cannot use s3Client (variable of type *s3.Client) as *client.Client value in argument to xray.AWS`

Quoting the initial body of this issue for context. Looking at the [README](https://github.com/aws/aws-xray-sdk-go/#readme) under "https://github.com/aws/aws-xray-sdk-go/#readme" it seems like to use xray with sdkv2 you need to perform two operations
1. `awsv2.AWSV2Instrumentor(&cfg.APIOptions)`
2. manually call `xray.BeginSegment` and defer its closure for each API call made with that client

This is a regression in the xray integration from v1.

Does this package provide a way to configure a client so that all calls are instrumented without requiring the consumer to do it each time?
