### ISSUE TITLE
runtime panic "cannot set embedded pointer to unexported struct: sampling.samplingRule"

### ISSUE THREAD

**Issue by rvdwijngaard** [aws/aws-xray-sdk-go#68] opened 2018-09-26 08:44 UTC
latest version of this package gives a runtime error because of unexported embedded struct samplingRule. 

I already made #67 to fix this.

**Comment by yogiraj07** [comment] 2018-09-26 18:03
Hi @rvdwijngaard ,
Thank you for the contribution, I have merged the PR.

Best,
Yogi

**Comment by yogiraj07** [comment] 2018-09-26 22:29
Hi @rvdwijngaard ,
Can you help us to reproduce this issue (steps or sample app might help), since we could not reproduce on our side. What is your use case and the Go Version you are using.

Best,
Yogi

**Comment by yogiraj07** [comment] 2018-09-28 01:27
Hi @rvdwijngaard ,
We have made `1.0.0-rc.7` release : https://github.com/aws/aws-xray-sdk-go/releases/tag/v1.0.0-rc.7.
Please feel free to open the issue, if you have any questions.
Thanks,
Yogi

**Closed by yogiraj07** 2018-09-28 01:27 UTC
